# Generated by Django 3.0.7 on 2020-09-17 11:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(default=1)),
                ('total_item', models.IntegerField(default=1)),
                ('grand_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('name', models.CharField(blank=True, default='Name', max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=70, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('DC', 'Debit Card'), ('NB', 'Net Banking'), ('PYPL', 'PayPal'), ('PHPE', 'PhonePe'), ('PYTM', 'Paytm')], max_length=30, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('PG', 'Pending'), ('PD', 'Paid'), ('F', 'Failed')], max_length=30, null=True)),
                ('remarks', models.CharField(blank=True, default='success', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/product')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('drink', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('calories', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('veg', models.BooleanField(default=False)),
                ('special', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_method', models.CharField(choices=[('DC', 'Debit Card'), ('NB', 'Net Banking'), ('PYPL', 'PayPal'), ('PHPE', 'PhonePe'), ('PYTM', 'Paytm')], max_length=30)),
                ('refund_status', models.CharField(choices=[('PG', 'Pending'), ('F', 'Failed'), ('C', 'Canceled'), ('RF', 'Refund Initiated'), ('RC', 'Refund Completed')], max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('UPG', 'Under Processing'), ('RFD', 'Ready for Delivery'), ('OFD', 'Out for delivery'), ('CBU', 'Canceled by User'), ('C', 'Canceled'), ('R', 'Returned'), ('D', 'Delivered')], max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('Expected_Dy', models.DateTimeField(default=datetime.datetime(2020, 9, 17, 19, 28, 18, 284768))),
                ('shipped_by', models.CharField(blank=True, max_length=100, null=True)),
                ('shipped_through', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
            ],
        ),
    ]
