# Generated by Django 3.0.7 on 2020-09-18 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='Expected_Dy',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 8, 59, 58, 712901)),
        ),
    ]
