# Generated by Django 3.0.7 on 2020-09-18 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200918_0659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderManagement',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Expected_Dy',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 9, 57, 6, 533611)),
        ),
    ]
