# Generated by Django 3.0.7 on 2020-09-18 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200918_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='Expected_Dy',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 10, 18, 40, 246789)),
        ),
    ]
