# Generated by Django 3.0.7 on 2020-09-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200918_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='Expected_Dy',
        ),
        migrations.AddField(
            model_name='delivery',
            name='Expected_Delivery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
