# Generated by Django 3.0.7 on 2020-09-18 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200918_0822'),
        ('company', '0002_auto_20200918_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstack',
            name='orders_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Order'),
            preserve_default=False,
        ),
    ]
